"""Add itinerary_id to maps table

Revision ID: 16519e1665a9
Revises: 1f639083cd86
Create Date: 2025-11-13 14:55:17.377241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16519e1665a9'
down_revision: Union[str, Sequence[str], None] = '1f639083cd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('itinerary_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'maps', 'itineraries', ['itinerary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maps', type_='foreignkey')
    op.drop_column('maps', 'itinerary_id')
    # ### end Alembic commands ###
